words = [
    'PYTHON', 'PROGRAMMING', 'COMPUTER', 'ALPHABET', 'SCIENCE', 'ENGINEER',
    'SOFTWARE', 'KEYBOARD', 'MONITOR', 'FUNCTION', 'VARIABLE', 'ITERATE',
    'GUESSING', 'RANDOM', 'SET', 'WHILE', 'LOOP', 'PROJECT', 'HANGMAN'
]